version: '3'
services:
    go:
        build:
            context: .
            dockerfile: ./infra/DockerFile.bk
        command: /bin/sh -c "go run main.go"
        stdin_open: true
        tty: true
        image: backend
        volumes:
            - ./backend:/app
        ports:
            - 8080:8080
        depends_on:
            - "db"

    db:
        build:
            context: .
            dockerfile: ./infra/DockerFile.db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ppp
            MYSQL_DATABASE: another
            MYSQL_USER: user
            MYSQL_PASSWORD: ppp
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - db-data:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306

    front:
        build:
            context: .
            dockerfile: ./infra/DockerFile.ft
        volumes: 
            - ./front/my-app:/app
        ports: 
            - 3000:3000
        command: "yarn start"

volumes: 
    db-data:
        driver: local