FROM golang:latest

RUN mkdir /app
WORKDIR /app

RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/jinzhu/gorm
RUN go get -u github.com/labstack/echo
RUN go get github.com/labstack/echo/middleware

CMD go run main.go